#!/bin/env bash
# Script to configure Nginx with a custom HTTP response header

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Define the custom header value
header_value=$(hostname)

# Configure Nginx to include the custom header
sudo bash -c "cat << EOF > /etc/nginx/conf.d/custom_response_header.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header X-Served-By $header_value;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
    }
}
EOF"

# Restart Nginx to apply changes
sudo systemctl restart nginx
