#!/usr/bin/env bash
#Process and PID file

deletes='rm /var/run/myscript.pid; exit $?'

echo $$ > "/var/run/myscript.pid"
trap 'echo "I hate the kill command"; '"$deletes" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap ''"$deletes" SIGQUIT

while true; do
	echo "To infinity and beyond"
done
